In [ ]:
# numpy : 수학과 데이터 분석을 쉽게할 수있도록 도와주는 라이브러리
# ndarray : 숫자를 여러 차원으로 표현가능하게 하는 배열


In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b

array([5, 7, 9])

In [ ]:
# 1차원 nbarray 생성
np.array([1,2,3,4])

arr1 = np.array([1,2,3,4]) #넘파이로 이루어진 다중배열 
arr2 = [1,2,3,4] #파이선 리스트

print(type(arr1))
print(type(arr2)) 


<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# 1차원 배열 : 숫자가 한줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로,세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러 장 겹친 입체 모양

arr2 = np.array([[1,2,3,4],
                [5,6,7,8]])

arr3 = np.array([[[1,2,3,4],[1,2,3,4]],
                [[1,2,3,4],[1,2,3,4]]])

print(arr2)

print()
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [1]:
import numpy as np

a = np.array([1,2,3,4])

print(a+1)
print(a+2)

[2 3 4 5]
[3 4 5 6]


In [ ]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr.shape) #(모양 : 층,행,열)
print(arr.ndim) #(차원 표시)

(2, 2, 2)
3


In [6]:
# 배열의 차원 수 : ndim
arr1 = np.array([1,2,3,4])

arr2 = np.array([[1,2,3,4],
                [5,6,7,8]])

arr3 = np.array([[[1,2,3,4],[1,2,3,4]],
                [[1,2,3,4],[1,2,3,4]]])
print(arr2.ndim)
print(arr3.ndim)


# 배열의 형태 : shape

print(arr2.shape)
print(arr3.shape)

# size : 배열 요소의 총 개수
print(arr2.size) #8
print(arr3.size) #16

# dtype : 배열 요소의 데이터 타입

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# itemsize : 배열 원소 하나가 차지하는 메모리 크기
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

# data : 배열의 실제 데이터가 저장된 메모리 버퍼(buffer 주소)
# 
# print(arr1.dtype)

print(arr2.data)
print(arr3.data) 

2
3
(2, 4)
(2, 2, 4)
8
16
int64
int64
int64
8
8
8


In [ ]:
# ndrrayT : 전치 행렬(행/열을 서로 바꾸는 것)

arr = np.array([[1,2,3],
                [4,5,6]])

print(arr) #원래 배열

print(arr.T) #전치 배열

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [9]:
#ndArray.flatten() : 1차원으로 펼치기

arr = np.array([[1,2,3],
                [4,5,6]])

print("원래 배열")
print(arr)

print("1차원으로 펼친 배열")
print(arr.flatten())

#flatten()은 복사본(copy)를 만든다.

flat = arr.flatten()
flat[0] = 100

print(arr)
print(flat)

원래 배열
[[1 2 3]
 [4 5 6]]
1차원으로 펼친 배열
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[100   2   3   4   5   6]


In [10]:
# nbarray.reshape() : 배열 모양 바꾸기

arr = np.array([[1, 2, 3 ,4, 5, 6]])

print("원래 배열")
print(arr)

arr2 = arr.reshape(2,3) # 2행 3열로 반환

print("reshape 배열")
print(arr2)

원래 배열
[[1 2 3 4 5 6]]
reshape 배열
[[1 2 3]
 [4 5 6]]


In [13]:
# nbarray.sum() : 합계 구하기
# nbArray.mean() : 평균구하기
# axis 옵션
# axis : 어느 축을 기준으로 계산할 것 인가
# axis=0 : 열 방향의 합
# axis=1 : 행 방향의 열

arr = np.array([[1,2,3],
                [4,5,6]])
print("전체 합 ")
print("sum =",arr.sum())
print("yeol_sum =",arr.sum(axis=0))
print("hang_sum =",arr.sum(axis=1))

print("전체 평균")
print("avg =",arr.mean())
print("yeol_avg =",arr.mean(axis=0))
print("hang_avg =",arr.mean(axis=1))

전체 합 
sum = 21
yeol_sum = [5 7 9]
hang_sum = [ 6 15]
전체 평균
avg = 3.5
yeol_avg = [2.5 3.5 4.5]
hang_avg = [2. 5.]


In [14]:
#nbArray.min() : 최솟값 구하기
#nbArray.max() : 최댓값 구하기

# axis 옵션
# axis=0 : 열 방향의 합
# axis=1 : 행 방향의 열

arr = np.array([[1,2,3],
                [4,5,6]])
print("최솟값 구하기 ")
print("min =",arr.min())
print("yeol_min =",arr.min(axis=0))
print("hang_min =",arr.min(axis=1))

print("최댓값 구하기")
print("max =",arr.max())
print("yeol_max =",arr.max(axis=0))
print("hang_max =",arr.max(axis=1))

최솟값 구하기 
min = 1
yeol_min = [1 2 3]
hang_min = [1 4]
최댓값 구하기
max = 6
yeol_max = [4 5 6]
hang_max = [3 6]


In [1]:
import numpy as np

# 1) np.zeros(shape)
# 지정한 모양으로 배열을 만들고, 모든 원소를 0으로 채움
# - 주로 초기값이 0인 배열이 필요할때 사용(누적합,버퍼,마스크 등)
# - shape은 튜플로 넣음: (행,열) 또는 (층,행,열)

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 2) np.ones(shape)
# - 지정한 shape으로 배열을 만들고, 모든 원소를 1로 채움
# - 기준 값을 1로 시작하거나, 가중치/마스의 기본값으로 자주 사용

np.ones((2, 3, 4))
# 모든 원소가 1인 3차원 배열 생성
# (2, 3, 4) => 2층, 각 층은  3행 4열


In [16]:
# 3) np.full(shape, full_value)

np.full((4,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [15]:
# 4) *_like 계열 : np.zeros_like / np.ones_like / np.full_like
# - like는 말 그대로 다른 배열을 보고 그대로 따라 만든다
# - 즉, 기존 배열의 shape을 그대로 가져와서 새 배열을 만든다.

# 장점
# - shape을 매번 직접 적을 필요가 없음(실수 줄어듦)
# - 기본적으로 dtype도 원본을 따라감(원과 같은 타입으로 안전하게 생성 가능)

arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

np.zeros_like(arr2)
# array([[0, 0, 0, 0],
#        [0, 0, 0, 0]])

np.ones_like(arr2)
# array([[1, 1, 1, 1],
#        [1, 1, 1, 1]])

np.full_like(arr2, 2)
# array([[2, 2, 2, 2],
#        [2, 2, 2, 2]])

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [17]:
import numpy as np

# np.random 모듈은 다양한 난수 생성 기능 제공
# 머신러닝, 시뮬레이션, 데이터 생성, 테스트 데이터 제작 등에 사용

# 1) randint(시작값, 끝값, size)
# 지정한 범위 안에서 정수형 난수 생성
# - 시작값 이상
# - 끝값 미만(끝값은 포함되지 않음)
# - size는 생성할 배열의 shape(모양)

np.random.randint(-100, 100, (2, 3))
# - -100이상 100미만의 정수
# - 2행 3열의 배열 생성
# - 실행할 때마다 다른 값이 나옴


# 2) seed(숫자)
# 난수 생성의 초기 상태 고정
# 같은 seed를 주면 항상 같은 난수 결과가 나옴

np.random.seed(1) # 난수 생성 기준을 1로 고정
np.random.randint(0, 10, (2, 3))
# seed=1 기준으로 항상 같은 난수 배열이 생성됨

np.random.seed(2)
np.random.randint(0, 10, (2, 3))
# seed=2 기준의 고정된 난수 생성

np.random.randint(0, 10, (2, 2, 3))
# 0 이상 10 미만 정수
# shape = (2, 2, 3)
# 2층, 각 층마다 2행 3열 구조의 3차원 배열 생성

array([[[2, 1, 5],
        [4, 4, 5]],

       [[7, 3, 6],
        [4, 3, 7]]], dtype=int32)

In [18]:

import numpy as np

# 인덱싱(Indexing) : 특정 위치의 하나의 값을 가져오는 방법
# 슬라이싱(Slicing) : 일정 범위를 잘라서 여러 값을 가져오는 방법

arr1 = np.array([1, 2, 3, 4]) # 1차원 배열, shape = (4,)
arr2 = np.array([[1, 2, 3, 4], # 2차원 배열, shape = (2, 4)
                 [5, 6, 7, 8]])


# === 1차원 배열 인덱싱 ===
print("파이썬 기본 리스트 예시")
li = [1, 2, 3, 4]
print(li[0])

print("1차원 배열 인덱싱")
print(arr1[0])


# === 1차원 배열 슬라이싱 ===
# 기본 형태 : arr1[시작:끝:보폭]
# 시작 포함, 끝은 제외

print("1차원 배열 슬라이싱")
print(arr1[1:3:])
# 1번 인덱스부터 3번 인덱스 "전"까지
# arr1[1], arr1[2]


# === 2차원 배열 인덱싱 ===
# 기본 형태 : arr2[행, 열]

print("2차원 배열 인덱싱")
print(arr2[0, 1])
# 첫 번째 행(0번), 두 번째 열(1번)

print(arr2[1, 2])
# 두 번째 행(1번), 세 번째 열(2번)


# === 2차원 배열 슬라이싱 ===
# 기본 형태 : arr2[행 범위, 열 범위]

print("2차원 배열의 슬라이싱")
print(arr2[1:2, 1:3])
# 행 : 1번부터 2번 직전 -> 1번 행만
# 열 : 1번부터 3번 직전 -> 1번, 2번 열


# Fancy 인덱싱 : 인덱스 번호를 리스트/배열로 여러 개 전달

print("1차원 배열 fancy 인덱싱")
print(arr1[[0, 1, 3]])
# 0번, 1번, 3번 인덱스를 한 번에 선택
# 결과 : [1, 2, 4]

print("2차원 배열 fancy 인덱싱")
print(arr2[[0, 1], [1, 3]])
# (0, 1) 위치와 (1, 2)위치를 각각 선택
# -> arr2[0, 1] = 2
# -> arr2[1, 3] = 8
# 결과 : [2, 8]

print("fancy 인덱싱 + 슬라이싱")
print(arr2[:, [0, 3]])
# 행은 전체 선택(:)
# 열은 0번과 3번만 선택


# 논리값 인덱싱 : True/False 조건으로 필터링

print("논리값 인덱싱")
print(arr1[[True, False, True, True]])
print(arr1[arr1 > 2])

파이썬 기본 리스트 예시
1
1차원 배열 인덱싱
1
1차원 배열 슬라이싱
[2 3]
2차원 배열 인덱싱
2
7
2차원 배열의 슬라이싱
[[6 7]]
1차원 배열 fancy 인덱싱
[1 2 4]
2차원 배열 fancy 인덱싱
[2 8]
fancy 인덱싱 + 슬라이싱
[[1 4]
 [5 8]]
논리값 인덱싱
[1 3 4]
[3 4]
