In [ ]:
# numpy : 수학과 데이터 분석을 쉽게할 수있도록 도와주는 라이브러리
# ndarray : 숫자를 여러 차원으로 표현가능하게 하는 배열


In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b

array([5, 7, 9])

In [ ]:
# 1차원 nbarray 생성
np.array([1,2,3,4])

arr1 = np.array([1,2,3,4]) #넘파이로 이루어진 다중배열 
arr2 = [1,2,3,4] #파이선 리스트

print(type(arr1))
print(type(arr2)) 


<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# 1차원 배열 : 숫자가 한줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로,세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러 장 겹친 입체 모양

arr2 = np.array([[1,2,3,4],
                [5,6,7,8]])

arr3 = np.array([[[1,2,3,4],[1,2,3,4]],
                [[1,2,3,4],[1,2,3,4]]])

print(arr2)

print()
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [1]:
import numpy as np

a = np.array([1,2,3,4])

print(a+1)
print(a+2)

[2 3 4 5]
[3 4 5 6]


In [ ]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr.shape) #(모양 : 층,행,열)
print(arr.ndim) #(차원 표시)

(2, 2, 2)
3


In [6]:
# 배열의 차원 수 : ndim
arr1 = np.array([1,2,3,4])

arr2 = np.array([[1,2,3,4],
                [5,6,7,8]])

arr3 = np.array([[[1,2,3,4],[1,2,3,4]],
                [[1,2,3,4],[1,2,3,4]]])
print(arr2.ndim)
print(arr3.ndim)


# 배열의 형태 : shape

print(arr2.shape)
print(arr3.shape)

# size : 배열 요소의 총 개수
print(arr2.size) #8
print(arr3.size) #16

# dtype : 배열 요소의 데이터 타입

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# itemsize : 배열 원소 하나가 차지하는 메모리 크기
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

# data : 배열의 실제 데이터가 저장된 메모리 버퍼(buffer 주소)
# 
# print(arr1.dtype)

print(arr2.data)
print(arr3.data) 

2
3
(2, 4)
(2, 2, 4)
8
16
int64
int64
int64
8
8
8


In [ ]:
# ndrrayT : 전치 행렬(행/열을 서로 바꾸는 것)

arr = np.array([[1,2,3],
                [4,5,6]])

print(arr) #원래 배열

print(arr.T) #전치 배열

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [9]:
#ndArray.flatten() : 1차원으로 펼치기

arr = np.array([[1,2,3],
                [4,5,6]])

print("원래 배열")
print(arr)

print("1차원으로 펼친 배열")
print(arr.flatten())

#flatten()은 복사본(copy)를 만든다.

flat = arr.flatten()
flat[0] = 100

print(arr)
print(flat)

원래 배열
[[1 2 3]
 [4 5 6]]
1차원으로 펼친 배열
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[100   2   3   4   5   6]


In [10]:
# nbarray.reshape() : 배열 모양 바꾸기

arr = np.array([[1, 2, 3 ,4, 5, 6]])

print("원래 배열")
print(arr)

arr2 = arr.reshape(2,3) # 2행 3열로 반환

print("reshape 배열")
print(arr2)

원래 배열
[[1 2 3 4 5 6]]
reshape 배열
[[1 2 3]
 [4 5 6]]


In [13]:
# nbarray.sum() : 합계 구하기
# nbArray.mean() : 평균구하기
# axis 옵션
# axis : 어느 축을 기준으로 계산할 것 인가
# axis=0 : 열 방향의 합
# axis=1 : 행 방향의 열

arr = np.array([[1,2,3],
                [4,5,6]])
print("전체 합 ")
print("sum =",arr.sum())
print("yeol_sum =",arr.sum(axis=0))
print("hang_sum =",arr.sum(axis=1))

print("전체 평균")
print("avg =",arr.mean())
print("yeol_avg =",arr.mean(axis=0))
print("hang_avg =",arr.mean(axis=1))

전체 합 
sum = 21
yeol_sum = [5 7 9]
hang_sum = [ 6 15]
전체 평균
avg = 3.5
yeol_avg = [2.5 3.5 4.5]
hang_avg = [2. 5.]


In [14]:
#nbArray.min() : 최솟값 구하기
#nbArray.max() : 최댓값 구하기

# axis 옵션
# axis=0 : 열 방향의 합
# axis=1 : 행 방향의 열

arr = np.array([[1,2,3],
                [4,5,6]])
print("최솟값 구하기 ")
print("min =",arr.min())
print("yeol_min =",arr.min(axis=0))
print("hang_min =",arr.min(axis=1))

print("최댓값 구하기")
print("max =",arr.max())
print("yeol_max =",arr.max(axis=0))
print("hang_max =",arr.max(axis=1))

최솟값 구하기 
min = 1
yeol_min = [1 2 3]
hang_min = [1 4]
최댓값 구하기
max = 6
yeol_max = [4 5 6]
hang_max = [3 6]
