In [ ]:
# numpy : 수학과 데이터 분석을 쉽게할 수있도록 도와주는 라이브러리
# ndarray : 숫자를 여러 차원으로 표현가능하게 하는 배열


In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b

array([5, 7, 9])

In [ ]:
# 1차원 nbarray 생성
np.array([1,2,3,4])

arr1 = np.array([1,2,3,4]) #넘파이로 이루어진 다중배열 
arr2 = [1,2,3,4] #파이선 리스트

print(type(arr1))
print(type(arr2)) 


<class 'numpy.ndarray'>
<class 'list'>


In [6]:
# 1차원 배열 : 숫자가 한줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로,세로로 된 표 모양
# 3차원 배열 : 2차원 배열이 여러 장 겹친 입체 모양

arr2 = np.array([[1,2,3,4],
                [5,6,7,8]])

arr3 = np.array([[[1,2,3,4],[1,2,3,4]],
                [[1,2,3,4],[1,2,3,4]]])

print(arr2)

print()
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
